# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   labels:
#     app: pingdirectory
#   name: pingdirectory-gp2
# mountOptions:
# - discard
# parameters:
#   type: gp2
# provisioner: kubernetes.io/aws-ebs
# reclaimPolicy: Delete
# volumeBindingMode: WaitForFirstConsumer

# ---
apiVersion: v1
data:
  K8S_STATEFUL_SET_NAME: pingdirectory
  K8S_STATEFUL_SET_SERVICE_NAME: pingdirectory-cluster
  ORCHESTRATION_TYPE: KUBERNETES
  SERVER_PROFILE_URL: https://github.com/Technical-Enablement-PingIdentity/BXFinance-ServerProfiles
  SERVER_PROFILE_PATH: profiles/pingdirectory
  ROOT_USER_PASSWORD_FILE: /opt/staging/pwd
  ADMIN_USER_PASSWORD_FILE: /opt/staging/pwd
  ENCRYPTION_PASSWORD_FILE: /opt/staging/pwd
  MAX_HEAP_SIZE: 768m
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    role: pingdirectory
  name: pingdirectory-environment-variables

---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingdirectory
  name: pingdirectory
spec:
  ports:
  - name: ldaps
    port: 1636
    targetPort: 636
  - name: ssl
    port: 1443
    targetPort: 443
  - name: consent
    port: 2443
    targetPort: 2443
  - name: ldap
    port: 389
    targetPort: 389
  selector:
    role: pingdirectory

---

apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingdirectory
  name: pingdirectory-cluster
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
  - name: ldaps
    port: 636
  selector:
    role: pingdirectory
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    role: pingdirectory
  name: pingdirectory
spec:
  replicas: 1
  selector:
    matchLabels:
      role: pingdirectory
  serviceName: pingdirectory-cluster
  template:
    metadata:
      labels:
        role: pingdirectory
      name: pingdirectory
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: global-env-vars
        # - secretRef:
        #     name: server-profile-url
        #     optional: true
        - secretRef:
            name: devops-secret
            optional: true
        - configMapRef:
            name: pingdirectory-environment-variables
        image: pingidentity/pingdirectory:2012-8.2.0.0
        env:
        - name: PD_PROFILE_SHA
          value: ${pingdirectorySha}
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - /preStop.sh
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /opt/liveness.sh
          initialDelaySeconds: 300
          periodSeconds: 30
        name: pingdirectory
        ports:
        - containerPort: 636
        - containerPort: 443
        - containerPort: 2443
        - containerPort: 389
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /opt/liveness.sh
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "1"
            memory: 8Gi
        volumeMounts:
        - mountPath: /opt/out
          name: out-dir
        - name: pingdirectory-license
          mountPath: "/opt/in/pd.profile/server-root/pre-setup/PingDirectory.lic"
          subPath: PingDirectory.lic
          readOnly: true
      terminationGracePeriodSeconds: 300
      volumes:
      - name: out-dir
        persistentVolumeClaim:
          claimName: out-dir
      - name: pingdirectory-license
        secret:
          secretName: pingdirectory-license
  volumeClaimTemplates:
  - metadata:
      name: out-dir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: gp2
